version: "3"
services:
  envoy:
    build: docker/envoy
    image: netoviz/envoy
    container_name: nv_envoy
    restart: always
    env_file:
      - .env
    extra_hosts:
      - netoviz:${NETOVIZ_HOST_ADDR}
    ports:
      - ${NETOVIZ_GRPC_WEB_PORT}:8080
      - ${ENVOY_MGMT_PORT}:9901
