version: "3"
services:
  envoy:
    build: docker/envoy
    image: netoviz/envoy
    container_name: nv-envoy
    restart: always
    env_file: .env
    ports:
      - "${NETOVIZ_GRPC_WEB_PORT}:${NETOVIZ_GRPC_WEB_LISTEN}"
      - "${NETOVIZ_PROXY_MGMT_PORT}:${NETOVIZ_PROXY_MGMT_LISTEN}"
