version: "3"
services:
  proxy:
    build: docker/envoy
    image: netoviz/envoy
    env_file: .env
    ports:
      - "${NETOVIZ_GRPC_WEB_PORT}:${NETOVIZ_GRPC_WEB_LISTEN}"
      - "${NETOVIZ_PROXY_MGMT_PORT}:${NETOVIZ_PROXY_MGMT_LISTEN}"
