version: "3"
services:
  envoy:
    build: docker/envoy
    image: netoviz/envoy
    container_name: nv_envoy
    restart: always
    extra_hosts:
      - netoviz:${NETOVIZ_HOST_ADDR}
    ports:
      - 8080:8080
      - 9901:9901
