/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf')
var goog = jspb
var global = Function('return this')()

goog.exportSymbol('proto.netoviz.Alert', null, global)
goog.exportSymbol('proto.netoviz.AlertReply', null, global)
goog.exportSymbol('proto.netoviz.AlertRequest', null, global)
goog.exportSymbol('proto.netoviz.GraphName', null, global)
goog.exportSymbol('proto.netoviz.GraphReply', null, global)
goog.exportSymbol('proto.netoviz.GraphRequest', null, global)
goog.exportSymbol('proto.netoviz.ModelReply', null, global)
goog.exportSymbol('proto.netoviz.ModelRequest', null, global)

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.GraphRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.GraphRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.GraphRequest.displayName = 'proto.netoviz.GraphRequest'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.GraphRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.netoviz.GraphRequest.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.GraphRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.GraphRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        graphName: jspb.Message.getFieldWithDefault(msg, 1, 0),
        modelFile: jspb.Message.getFieldWithDefault(msg, 2, ''),
        alertHost: jspb.Message.getFieldWithDefault(msg, 3, ''),
        depth: jspb.Message.getFieldWithDefault(msg, 4, 0),
        aggregate: jspb.Message.getFieldWithDefault(msg, 5, false),
        reverse: jspb.Message.getFieldWithDefault(msg, 6, false),
        fitGrid: jspb.Message.getFieldWithDefault(msg, 7, false)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.GraphRequest}
 */
proto.netoviz.GraphRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.GraphRequest()
  return proto.netoviz.GraphRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.GraphRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.GraphRequest}
 */
proto.netoviz.GraphRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {!proto.netoviz.GraphName} */ (reader.readEnum())
        msg.setGraphName(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setModelFile(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setAlertHost(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readUint32())
        msg.setDepth(value)
        break
      case 5:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setAggregate(value)
        break
      case 6:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setReverse(value)
        break
      case 7:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setFitGrid(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.GraphRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.GraphRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.GraphRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getGraphName()
  if (f !== 0.0) {
    writer.writeEnum(1, f)
  }
  f = message.getModelFile()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getAlertHost()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getDepth()
  if (f !== 0) {
    writer.writeUint32(4, f)
  }
  f = message.getAggregate()
  if (f) {
    writer.writeBool(5, f)
  }
  f = message.getReverse()
  if (f) {
    writer.writeBool(6, f)
  }
  f = message.getFitGrid()
  if (f) {
    writer.writeBool(7, f)
  }
}

/**
 * optional GraphName graph_name = 1;
 * @return {!proto.netoviz.GraphName}
 */
proto.netoviz.GraphRequest.prototype.getGraphName = function () {
  return /** @type {!proto.netoviz.GraphName} */ (jspb.Message.getFieldWithDefault(
    this,
    1,
    0
  ))
}

/** @param {!proto.netoviz.GraphName} value */
proto.netoviz.GraphRequest.prototype.setGraphName = function (value) {
  jspb.Message.setProto3EnumField(this, 1, value)
}

/**
 * optional string model_file = 2;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getModelFile = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setModelFile = function (value) {
  jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string alert_host = 3;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getAlertHost = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setAlertHost = function (value) {
  jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional uint32 depth = 4;
 * @return {number}
 */
proto.netoviz.GraphRequest.prototype.getDepth = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0))
}

/** @param {number} value */
proto.netoviz.GraphRequest.prototype.setDepth = function (value) {
  jspb.Message.setProto3IntField(this, 4, value)
}

/**
 * optional bool aggregate = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.netoviz.GraphRequest.prototype.getAggregate = function () {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(
    this,
    5,
    false
  ))
}

/** @param {boolean} value */
proto.netoviz.GraphRequest.prototype.setAggregate = function (value) {
  jspb.Message.setProto3BooleanField(this, 5, value)
}

/**
 * optional bool reverse = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.netoviz.GraphRequest.prototype.getReverse = function () {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(
    this,
    6,
    false
  ))
}

/** @param {boolean} value */
proto.netoviz.GraphRequest.prototype.setReverse = function (value) {
  jspb.Message.setProto3BooleanField(this, 6, value)
}

/**
 * optional bool fit_grid = 7;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.netoviz.GraphRequest.prototype.getFitGrid = function () {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(
    this,
    7,
    false
  ))
}

/** @param {boolean} value */
proto.netoviz.GraphRequest.prototype.setFitGrid = function (value) {
  jspb.Message.setProto3BooleanField(this, 7, value)
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.GraphReply = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.GraphReply, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.GraphReply.displayName = 'proto.netoviz.GraphReply'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.GraphReply.prototype.toObject = function (opt_includeInstance) {
    return proto.netoviz.GraphReply.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.GraphReply} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.GraphReply.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        graphName: jspb.Message.getFieldWithDefault(msg, 1, 0),
        modelFile: jspb.Message.getFieldWithDefault(msg, 2, ''),
        json: jspb.Message.getFieldWithDefault(msg, 3, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.GraphReply}
 */
proto.netoviz.GraphReply.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.GraphReply()
  return proto.netoviz.GraphReply.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.GraphReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.GraphReply}
 */
proto.netoviz.GraphReply.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {!proto.netoviz.GraphName} */ (reader.readEnum())
        msg.setGraphName(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setModelFile(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setJson(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.GraphReply.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.GraphReply.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.GraphReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphReply.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getGraphName()
  if (f !== 0.0) {
    writer.writeEnum(1, f)
  }
  f = message.getModelFile()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getJson()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
}

/**
 * optional GraphName graph_name = 1;
 * @return {!proto.netoviz.GraphName}
 */
proto.netoviz.GraphReply.prototype.getGraphName = function () {
  return /** @type {!proto.netoviz.GraphName} */ (jspb.Message.getFieldWithDefault(
    this,
    1,
    0
  ))
}

/** @param {!proto.netoviz.GraphName} value */
proto.netoviz.GraphReply.prototype.setGraphName = function (value) {
  jspb.Message.setProto3EnumField(this, 1, value)
}

/**
 * optional string model_file = 2;
 * @return {string}
 */
proto.netoviz.GraphReply.prototype.getModelFile = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/** @param {string} value */
proto.netoviz.GraphReply.prototype.setModelFile = function (value) {
  jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string json = 3;
 * @return {string}
 */
proto.netoviz.GraphReply.prototype.getJson = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/** @param {string} value */
proto.netoviz.GraphReply.prototype.setJson = function (value) {
  jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.AlertRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.AlertRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.AlertRequest.displayName = 'proto.netoviz.AlertRequest'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.AlertRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.netoviz.AlertRequest.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.AlertRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.AlertRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        number: jspb.Message.getFieldWithDefault(msg, 1, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.AlertRequest}
 */
proto.netoviz.AlertRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.AlertRequest()
  return proto.netoviz.AlertRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.AlertRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.AlertRequest}
 */
proto.netoviz.AlertRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readUint32())
        msg.setNumber(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.AlertRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.AlertRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.AlertRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.AlertRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getNumber()
  if (f !== 0) {
    writer.writeUint32(1, f)
  }
}

/**
 * optional uint32 number = 1;
 * @return {number}
 */
proto.netoviz.AlertRequest.prototype.getNumber = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0))
}

/** @param {number} value */
proto.netoviz.AlertRequest.prototype.setNumber = function (value) {
  jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.Alert = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.Alert, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.Alert.displayName = 'proto.netoviz.Alert'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.Alert.prototype.toObject = function (opt_includeInstance) {
    return proto.netoviz.Alert.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.Alert} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.Alert.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, 0),
        host: jspb.Message.getFieldWithDefault(msg, 2, ''),
        severity: jspb.Message.getFieldWithDefault(msg, 3, ''),
        date: jspb.Message.getFieldWithDefault(msg, 4, ''),
        message: jspb.Message.getFieldWithDefault(msg, 5, ''),
        createdAt: jspb.Message.getFieldWithDefault(msg, 6, ''),
        updatedAt: jspb.Message.getFieldWithDefault(msg, 7, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.Alert}
 */
proto.netoviz.Alert.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.Alert()
  return proto.netoviz.Alert.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.Alert} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.Alert}
 */
proto.netoviz.Alert.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readUint32())
        msg.setId(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setHost(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setSeverity(value)
        break
      case 4:
        var value = /** @type {string} */ (reader.readString())
        msg.setDate(value)
        break
      case 5:
        var value = /** @type {string} */ (reader.readString())
        msg.setMessage(value)
        break
      case 6:
        var value = /** @type {string} */ (reader.readString())
        msg.setCreatedAt(value)
        break
      case 7:
        var value = /** @type {string} */ (reader.readString())
        msg.setUpdatedAt(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.Alert.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.Alert.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.Alert} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.Alert.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getId()
  if (f !== 0) {
    writer.writeUint32(1, f)
  }
  f = message.getHost()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getSeverity()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getDate()
  if (f.length > 0) {
    writer.writeString(4, f)
  }
  f = message.getMessage()
  if (f.length > 0) {
    writer.writeString(5, f)
  }
  f = message.getCreatedAt()
  if (f.length > 0) {
    writer.writeString(6, f)
  }
  f = message.getUpdatedAt()
  if (f.length > 0) {
    writer.writeString(7, f)
  }
}

/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.netoviz.Alert.prototype.getId = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0))
}

/** @param {number} value */
proto.netoviz.Alert.prototype.setId = function (value) {
  jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional string host = 2;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getHost = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setHost = function (value) {
  jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string severity = 3;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getSeverity = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setSeverity = function (value) {
  jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional string date = 4;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getDate = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setDate = function (value) {
  jspb.Message.setProto3StringField(this, 4, value)
}

/**
 * optional string message = 5;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getMessage = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setMessage = function (value) {
  jspb.Message.setProto3StringField(this, 5, value)
}

/**
 * optional string created_at = 6;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getCreatedAt = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setCreatedAt = function (value) {
  jspb.Message.setProto3StringField(this, 6, value)
}

/**
 * optional string updated_at = 7;
 * @return {string}
 */
proto.netoviz.Alert.prototype.getUpdatedAt = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ''))
}

/** @param {string} value */
proto.netoviz.Alert.prototype.setUpdatedAt = function (value) {
  jspb.Message.setProto3StringField(this, 7, value)
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.AlertReply = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.netoviz.AlertReply.repeatedFields_,
    null
  )
}
goog.inherits(proto.netoviz.AlertReply, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.AlertReply.displayName = 'proto.netoviz.AlertReply'
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.netoviz.AlertReply.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.AlertReply.prototype.toObject = function (opt_includeInstance) {
    return proto.netoviz.AlertReply.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.AlertReply} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.AlertReply.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        alertsList: jspb.Message.toObjectList(
          msg.getAlertsList(),
          proto.netoviz.Alert.toObject,
          includeInstance
        )
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.AlertReply}
 */
proto.netoviz.AlertReply.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.AlertReply()
  return proto.netoviz.AlertReply.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.AlertReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.AlertReply}
 */
proto.netoviz.AlertReply.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.netoviz.Alert()
        reader.readMessage(
          value,
          proto.netoviz.Alert.deserializeBinaryFromReader
        )
        msg.addAlerts(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.AlertReply.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.AlertReply.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.AlertReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.AlertReply.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getAlertsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.netoviz.Alert.serializeBinaryToWriter
    )
  }
}

/**
 * repeated Alert alerts = 1;
 * @return {!Array<!proto.netoviz.Alert>}
 */
proto.netoviz.AlertReply.prototype.getAlertsList = function () {
  return /** @type{!Array<!proto.netoviz.Alert>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.netoviz.Alert,
    1
  ))
}

/** @param {!Array<!proto.netoviz.Alert>} value */
proto.netoviz.AlertReply.prototype.setAlertsList = function (value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.netoviz.Alert=} opt_value
 * @param {number=} opt_index
 * @return {!proto.netoviz.Alert}
 */
proto.netoviz.AlertReply.prototype.addAlerts = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.netoviz.Alert,
    opt_index
  )
}

proto.netoviz.AlertReply.prototype.clearAlertsList = function () {
  this.setAlertsList([])
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.ModelRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.ModelRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.ModelRequest.displayName = 'proto.netoviz.ModelRequest'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.ModelRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.netoviz.ModelRequest.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.ModelRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.ModelRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {}

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.ModelRequest}
 */
proto.netoviz.ModelRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.ModelRequest()
  return proto.netoviz.ModelRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.ModelRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.ModelRequest}
 */
proto.netoviz.ModelRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.ModelRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.ModelRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.ModelRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.ModelRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.ModelReply = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.netoviz.ModelReply, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.ModelReply.displayName = 'proto.netoviz.ModelReply'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.netoviz.ModelReply.prototype.toObject = function (opt_includeInstance) {
    return proto.netoviz.ModelReply.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.netoviz.ModelReply} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.netoviz.ModelReply.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        json: jspb.Message.getFieldWithDefault(msg, 1, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.ModelReply}
 */
proto.netoviz.ModelReply.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.netoviz.ModelReply()
  return proto.netoviz.ModelReply.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.ModelReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.ModelReply}
 */
proto.netoviz.ModelReply.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setJson(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.ModelReply.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.netoviz.ModelReply.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.ModelReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.ModelReply.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getJson()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
}

/**
 * optional string json = 1;
 * @return {string}
 */
proto.netoviz.ModelReply.prototype.getJson = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/** @param {string} value */
proto.netoviz.ModelReply.prototype.setJson = function (value) {
  jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * @enum {number}
 */
proto.netoviz.GraphName = {
  GRAPH_UNKNOWN: 0,
  FORCE_SIMULATION: 1,
  DEPENDENCY: 2,
  NESTED: 3,
  DISTANCE: 4
}

goog.object.extend(exports, proto.netoviz)
