/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.netoviz.GraphReply', null, global);
goog.exportSymbol('proto.netoviz.GraphRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.GraphRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.netoviz.GraphRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.GraphRequest.displayName = 'proto.netoviz.GraphRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.netoviz.GraphRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.netoviz.GraphRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.netoviz.GraphRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    graphType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jsonName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    target: jspb.Message.getFieldWithDefault(msg, 3, ""),
    layer: jspb.Message.getFieldWithDefault(msg, 4, ""),
    depth: jspb.Message.getFieldWithDefault(msg, 5, 0),
    aggregate: jspb.Message.getFieldWithDefault(msg, 6, false),
    reverse: jspb.Message.getFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.GraphRequest}
 */
proto.netoviz.GraphRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.netoviz.GraphRequest;
  return proto.netoviz.GraphRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.GraphRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.GraphRequest}
 */
proto.netoviz.GraphRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGraphType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLayer(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDepth(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAggregate(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReverse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.GraphRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.netoviz.GraphRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.GraphRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraphType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJsonName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTarget();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLayer();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDepth();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getAggregate();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getReverse();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string graph_type = 1;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getGraphType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setGraphType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string json_name = 2;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getJsonName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setJsonName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string target = 3;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setTarget = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string layer = 4;
 * @return {string}
 */
proto.netoviz.GraphRequest.prototype.getLayer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.netoviz.GraphRequest.prototype.setLayer = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint32 depth = 5;
 * @return {number}
 */
proto.netoviz.GraphRequest.prototype.getDepth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.netoviz.GraphRequest.prototype.setDepth = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool aggregate = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.netoviz.GraphRequest.prototype.getAggregate = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.netoviz.GraphRequest.prototype.setAggregate = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool reverse = 7;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.netoviz.GraphRequest.prototype.getReverse = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 7, false));
};


/** @param {boolean} value */
proto.netoviz.GraphRequest.prototype.setReverse = function(value) {
  jspb.Message.setProto3BooleanField(this, 7, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.netoviz.GraphReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.netoviz.GraphReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.netoviz.GraphReply.displayName = 'proto.netoviz.GraphReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.netoviz.GraphReply.prototype.toObject = function(opt_includeInstance) {
  return proto.netoviz.GraphReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.netoviz.GraphReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    graphType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jsonName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    json: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.netoviz.GraphReply}
 */
proto.netoviz.GraphReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.netoviz.GraphReply;
  return proto.netoviz.GraphReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.netoviz.GraphReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.netoviz.GraphReply}
 */
proto.netoviz.GraphReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGraphType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJson(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.netoviz.GraphReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.netoviz.GraphReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.netoviz.GraphReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.netoviz.GraphReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraphType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJsonName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getJson();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string graph_type = 1;
 * @return {string}
 */
proto.netoviz.GraphReply.prototype.getGraphType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.netoviz.GraphReply.prototype.setGraphType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string json_name = 2;
 * @return {string}
 */
proto.netoviz.GraphReply.prototype.getJsonName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.netoviz.GraphReply.prototype.setJsonName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string json = 3;
 * @return {string}
 */
proto.netoviz.GraphReply.prototype.getJson = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.netoviz.GraphReply.prototype.setJson = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.netoviz);
