@startuml
class AlertTable {
    +addAlert()
    +alerts()
    +allAlerts()
}
AlertTable -- Alert
class APIBase {
    +constructor()
    +getModels()
    +readLayoutJSON()
    +toForceSimulationTopologyData()
    +toDependencyTopologyData()
    +toNestedTopologyData()
    +toDistanceTopologyData()
    +getGraphData()
    +splitAlertHost()
}
APIBase -- CacheRfcTopologyDataConverter
class CacheRfcTopologyDataConverter {
    +constructor()
    -_checkCacheDir()
    -_readForceSimulationTopologyDataFromCacheJSON()
    -_readRfcTopologyDataFromJSON()
    -_writeCache()
    -_updateStatsOfTopologyJSON()
    -_foundOperativeCache()
    -_updateCacheTimeStamp()
    +toForceSimulationTopologyData()
}
class GRPCIntegrator {
    +toDependencyTopologyData()
    +toNestedTopologyData()
    +toDistanceTopologyData()
    +splitAlertHost()
}
GRPCIntegrator --|> APIBase
class RESTIntegrator {
    -_boolString2Bool()
    -_numberString2Number()
    -_printGraphQuery()
    -_makeGraphQuery()
    +toDependencyTopologyData()
    +toNestedTopologyData()
    +toDistanceTopologyData()
    +postGraphData()
}
RESTIntegrator --|> APIBase
class ShallowNestedNode {
    +constructor()
    -_setFamilyRelation()
    +layerPath()
    +layer()
    +isNode()
    +isRootNode()
    +isTp()
    +matchTpPath()
    +matchNodePath()
    +parentNodePaths()
    +parentTpPaths()
    +childNodePaths()
    +childTpPaths()
    +numberOfTps()
    +numberOfParentNodes()
    +numberOfChildNodes()
    +filterTpPath()
    +filterNodePath()
    +linkPath()
    +setCircle()
    +setRect()
    +setGridPosition()
}
class DeepNestedTopology {
    +constructor()
    +beforeCalcRootNodePosition()
    +setNodes()
    +splitNode()
    +isLeaf()
    -_overDepth()
    -_inTargetDepth()
    +assumeAsLeaf()
    +childNodePathsToCalcPosition()
    +childNodeFrom()
}
DeepNestedTopology --|> ShallowNestedTopology
DeepNestedTopology -- DeepNestedNode
class NestLayout {
    +constructor()
    +toData()
}
class ShallowNestedTopology {
    +constructor()
    +initialize()
    +beforeCalcRootNodePosition()
    +setGrid()
    +setNodes()
    +setNodesAs()
    +findLinkBetween()
    +setLinks()
    +setRootNodes()
    +findNodeByPath()
    +mapPathsToNodes()
    +calcRootNodePosition()
    -_singleParentChildNodePaths()
    +isLeaf()
    +assumeAsLeaf()
    +consoleDebug()
    -_calcNodeWHAsLeaf()
    -_calcChildrenWHList()
    -_calcNodeWHAsSubRoot()
    -_calcNodePosition()
    +childNodePathsToCalcPosition()
    +childNodeFrom()
    -_calcChildNodePosition()
    -_widthByTp()
    -_heightByTp()
    -_widthByChildNodes()
    -_heightByChildNodes()
    -_calcSubRootNodeWH()
    -_calcLeafNodeWH()
    -_calcTpPosition()
    -_operativeNodes()
    -_inoperativeNodes()
    -_operativeLinksIn()
    -_makeSupportTpLinks()
    +toData()
}
ShallowNestedTopology -- GridOperator
ShallowNestedTopology -- ShallowNestedNode
ShallowNestedTopology -- NestedLink
class NestedLink {
    +availableIn()
}
NestedLink --|> ForceSimulationLink
class AggregatedNestedNode {
    +constructor()
    -_aggregateWith()
}
AggregatedNestedNode --|> DeepNestedNode
AggregatedNestedNode -- AggregatedNodeAttribute
class AggregatedTopology {
    -_replaceChildrenByAggregatedNode()
    -_aggregatedNodeName()
    -_makeAggregateNode()
    -_uniqLayerPaths()
    -_classifyAggregateTarget()
    -_familyClassifier()
    -_makeFamilyClassifiers()
    -_layerClassifier()
    -_makeLayerClassifiers()
    -_makeClassifierProduction()
    -_combinedClassifier()
    -_makeCombinedClassifiers()
    -_aggregateChildNodes()
    +childNodePathsToCalcPosition()
}
AggregatedTopology --|> DeepNestedTopology
AggregatedTopology -- AggregatedNestedNode
AggregatedTopology -- Set
class DeepNestedNode {
    +constructor()
    +renameChildPath()
    -_duplicate()
    +splitNodeByParent()
}
DeepNestedNode --|> ShallowNestedNode
DeepNestedNode -- DeepNestedNode
class GridOperator {
    +constructor()
    -_setLayoutData()
    -_setXYGrid()
    -_initDefault()
    -_setXGridByInterval()
    -_setYGridByInterval()
    +positionByOrdinal()
    -_ordinal2coordinate()
    -_nextOrdinalPosition()
    +ordinalPositionByNodePath()
    +toData()
}
GridOperator -- NestLayout
class RfcL2TermPoint {
    +constructor()
}
RfcL2TermPoint --|> RfcTermPoint
RfcL2TermPoint -- RfcL2TermPointAttribute
class RfcL3NetworkAttribute {
    +constructor()
}
RfcL3NetworkAttribute --|> RfcModelBase
class RfcL3Network {
    +constructor()
    +newNode()
    +newLink()
}
RfcL3Network --|> RfcNetwork
RfcL3Network -- RfcL3NetworkAttribute
RfcL3Network -- RfcL3Node
RfcL3Network -- RfcL3Link
class RfcTopology {
    +constructor()
    +newNetwork()
}
RfcTopology --|> RfcModelBase
RfcTopology -- RfcNetwork
RfcTopology -- RfcL3Network
RfcTopology -- RfcL2Network
class RfcL3Link {
    +constructor()
}
RfcL3Link --|> RfcLink
RfcL3Link -- RfcL3LinkAttribute
class RfcL3TermPointAttribute {
    +constructor()
    +toHtml()
}
RfcL3TermPointAttribute --|> RfcModelBase
class RfcL2NetworkAttribute {
    +constructor()
}
RfcL2NetworkAttribute --|> RfcModelBase
class RfcL3TermPoint {
    +constructor()
}
RfcL3TermPoint --|> RfcTermPoint
RfcL3TermPoint -- RfcL3TermPointAttribute
class RfcL2Link {
    +constructor()
}
RfcL2Link --|> RfcLink
RfcL2Link -- RfcL2LinkAttribute
class RfcNode {
    +constructor()
    -_constructTermPoints()
    +newTP()
    -_constructSupportingNodes()
    +findTpByPath()
    -_makeChildren()
    +graphNode()
}
RfcNode --|> RfcModelBase
RfcNode -- RfcTermPoint
RfcNode -- RfcSupportingNode
RfcNode -- ForceSimulationNode
class RfcL3LinkAttribute {
    +constructor()
}
RfcL3LinkAttribute --|> RfcModelBase
class RfcL3Node {
    +constructor()
    +newTP()
}
RfcL3Node --|> RfcNode
RfcL3Node -- RfcL3NodeAttribute
RfcL3Node -- RfcL3TermPoint
class RfcL3NodeAttribute {
    +constructor()
    -_selectRouterId()
    +toHtml()
}
RfcL3NodeAttribute --|> RfcModelBase
RfcL3NodeAttribute -- RfcL3Prefix
class RfcNetwork {
    +constructor()
    -_constructSupportingNetworks()
    -_makeGraphNodesAsNode()
    -_makeGraphNodesAsTp()
    +makeGraphNodes()
    -_constructNodes()
    +newNode()
    -_constructLinks()
    +newLink()
    +makeGraphLinks()
    +isTypeLayer3()
    +isTypeLayer2()
}
RfcNetwork --|> RfcModelBase
RfcNetwork -- RfcNetworkTypes
RfcNetwork -- RfcSupportingNetwork
RfcNetwork -- RfcNode
RfcNetwork -- RfcLink
class RfcL2Node {
    +constructor()
    +newTP()
}
RfcL2Node --|> RfcNode
RfcL2Node -- RfcL2NodeAttribute
RfcL2Node -- RfcL2TermPoint
class RfcLink {
    +constructor()
    -_constructSupportingLinks()
    +graphLink()
}
RfcLink --|> RfcModelBase
RfcLink -- RfcLinkTpRef
RfcLink -- RfcSupportingLink
RfcLink -- ForceSimulationLink
class RfcL2TermPointAttribute {
    +constructor()
    +toHtml()
}
RfcL2TermPointAttribute --|> RfcModelBase
RfcL2TermPointAttribute -- RfcL2VlanIdName
class RfcTermPoint {
    +constructor()
    -_constructSupportingTermPoints()
    -_makeChildren()
    +graphNode()
    +graphLink()
}
RfcTermPoint --|> RfcModelBase
RfcTermPoint -- RfcSupportingTermPoint
RfcTermPoint -- ForceSimulationNode
RfcTermPoint -- ForceSimulationLink
class AggregatedNodeAttribute {
    +constructor()
    -_aggregatesNodeStr()
    +toHtml()
}
AggregatedNodeAttribute --|> RfcModelBase
class RfcL2NodeAttribute {
    +constructor()
    +toHtml()
}
RfcL2NodeAttribute --|> RfcModelBase
class RfcL2LinkAttribute {
    +constructor()
}
RfcL2LinkAttribute --|> RfcModelBase
class RfcModelBase {
    +constructor()
    -_constructDiffState()
}
RfcModelBase --|> BaseContainer
RfcModelBase -- DiffState
class RfcL2Network {
    +constructor()
    +newNode()
    +newLink()
}
RfcL2Network --|> RfcNetwork
RfcL2Network -- RfcL2NetworkAttribute
RfcL2Network -- RfcL2Node
RfcL2Network -- RfcL2Link
class DistanceTopology {
    +constructor()
    -_distanceCircleInterval()
    -_correctArrays()
    -_distanceCircleRadius()
    -_rewriteDistanceCircleRadius()
    -_makeNodeLayout()
    -_nodesInLayouts()
    -_makeSupportLinks()
    -_makeLinks()
    +toData()
}
DistanceTopology -- DistanceNode
DistanceTopology -- DistanceLink
class DistanceNode {
    +constructor()
    +layerPath()
    +isTypeNode()
    -_exists()
    +hasTargetRelation()
    +distance()
}
DistanceNode --|> ForceSimulationNode
class DistanceLink {
    +constructor()
    +layerPath()
    +isTypeTpTp()
    +isInLayer()
    +isConnectingNode()
    -_endNodePath()
    +isReverseLink()
}
DistanceLink --|> ForceSimulationLink
class NeighborMaker {
    +constructor()
    +markNeighborWithTarget()
    -_findAllTpTpLinksInLayerOf()
    -_markNeighbor()
    -_findNodeByPath()
    -_findAllLinksWithoutOrigin()
    -_findAllLinksWithOrigin()
}
NeighborMaker --|> RelationMakerBase
NeighborMaker -- NeighborRelation
NeighborMaker -- NeighborMaker
class RelationMakerBase {
    +constructor()
    +findTargetNode()
    +findTargetNodeByName()
    +findTargetNodeByPath()
    +consoleDebug()
}
class DiffState {
    +constructor()
    +detect()
}
class FamilyMaker {
    -_findNodeByPath()
    -_existsFamilyInNode()
    -_findAndMarkAsFamily()
    +markFamilyWithTarget()
}
FamilyMaker --|> RelationMakerBase
FamilyMaker -- FamilyRelation
FamilyMaker -- FamilyMaker
class BaseContainer {
    +sortUniq()
    +flatten()
}
BaseContainer -- Set
class DependencyTopology {
    +constructor()
    -_markFamilyWithTarget()
    -_setNetworks()
    +toData()
}
DependencyTopology -- DependencyNetwork
class DependencyNode {
    +constructor()
    +setPosition()
    +nodeWidth()
    +toData()
}
DependencyNode --|> ForceSimulationNode
DependencyNode -- DependencyConstants
class DependencyNetwork {
    +constructor()
    -_setPosition()
    -_calcX()
    -_layerHeight()
    -_calcY()
    -_setNodes()
    -_findNodeByPath()
    -_setTermPoints()
    -_isType()
    -_findAllNodesFrom()
    -_findAllTermPointsFrom()
    +toData()
}
DependencyNetwork -- DependencyConstants
DependencyNetwork -- DependencyNode
DependencyNetwork -- DependencyTermPoint
class DependencyTermPoint {
    +constructor()
    -_setCenterPosition()
    +setCenterPosition()
    -_calcX()
    -_calcY()
    +parentPath()
    +toData()
}
DependencyTermPoint --|> ForceSimulationNode
DependencyTermPoint -- DependencyConstants
class DependencyConstants {
    +constructor()
    +nodeWidth()
    +nodeHeight()
}
class ForceSimulationTopology {
    +constructor()
    -_makeNodes()
    -_findNodeByPath()
    -_makeParentRef()
    -_errorLinkEndNodeNotFound()
    -_resolveLinkRef()
    +toData()
}
ForceSimulationTopology --|> BaseContainer
ForceSimulationTopology -- RfcTopology
ForceSimulationTopology -- ForceSimulationNetwork
class ForceSimulationNode {
    +constructor()
    +addParent()
}
class ForceSimulationNetwork {
    +constructor()
}
class ForceSimulationLink {
    +constructor()
}
class NestedDiagramBuilder {
    +constructor()
    +selectXY()
    -_makeGridHandles()
    -_makeGridLines()
    -_makeGridLabels()
    -_gridObjectsFrom()
    -_makeGrids()
    +colorOfNode()
    -_makeColorTable()
    -_makeNodes()
    -_makeSupportTpLines()
    -_makeTpTpLines()
    +remakeLinkLines()
    -_makeTps()
    -_makeNodeLabels()
    -_makeTpLabels()
    -_makeGridFittingButton()
    +makeDiagramControlButtons()
    -_wholeNodes()
    -_wholeTermPoints()
    +makeAllDiagramElements()
}
NestedDiagramBuilder --|> MultilayerDiagramBase
NestedDiagramBuilder -- Set
NestedDiagramBuilder -- InterTpLinkCreator
class NestedDiagramOperator {
    -_findTargetRootNodes()
    -_selectNodeRectByPath()
    -_selectNodeLabelByPath()
    -_selectTpCircleByPath()
    -_selectTpLabelByPath()
    -_selectTpTpLineByPath()
    -_selectSupportTpLineByPath()
    -_selectGridLine()
    -_selectGridHandle()
    -_selectGridLabel()
    +findOperativeNodeByPath()
    +findInoperativeNodeByPath()
    +operativeNodesByName()
    +inoperativeNodesByName()
    -_updateNodeRectPosition()
    -_tpsInNode()
    -_updateTpCirclePosition()
    -_childNodesOfNode()
    -_moveRootNode()
    -_redrawLinkLines()
    -_updateGridLine()
    -_setGridHandler()
    -_setTpClassByPath()
    -_setLineClass()
    -_setLinkMouseHandler()
    -_setInitialZoom()
    -_setSVGZoom()
    +setSelectReady()
    +highlight()
    -_clearAllChecked()
    -_clearAllSelectReady()
    +clearAllAlertHighlight()
    -_setTpMouseHandler()
    +nodeClickHook()
    -_setNodeMouseHandler()
    -_maxWHOnGrid()
    -_gridFittingXY()
    +fitGrid()
    -_setGridFittingButtonHandler()
    +setAllDiagramElementsHandler()
}
NestedDiagramOperator --|> NestedDiagramBuilder
class NestedDiagramVisualizer {
    +afterDrawRfcTopologyDataHook()
    +saveLayout()
    +setUISideNodeClickHook()
    +nodeClickHook()
    -_FindOperativeParentAndHighlight()
    -_highlightParentOfInoperativeNodes()
    -_highlightOperativeNodes()
    +highlightByAlert()
}
NestedDiagramVisualizer --|> NestedDiagramOperator
class InterTpLinkCreator {
    +constructor()
    -_forEachTpTpLink()
    -_groupByOverlapLinks()
    -_slashLinks()
    -_backslashLinks()
    -_displaceYMidOfLinksIn()
    -_adjustLineOverlap()
    -_linksWith()
    +supportTpLinks()
    +tpTpLinks()
    +toData()
}
InterTpLinkCreator -- InterTpLink
InterTpLinkCreator -- Set
class InterTpLink {
    +constructor()
    +xMin()
    +yMin()
    +xMax()
    +yMax()
    -_height()
    -_width()
    +isSkewVertical()
    +isSkewHorizontal()
    +isSkewSlash()
    +isSkewBackslash()
    -_skewType()
    +hasOverlapIndex()
    -_inRange()
    -_inRangeX()
    -_inRangeYLow()
    -_inRangeYHigh()
    -_isNearYMid()
    +isOverlapX()
    -_isSameSkew()
    -_isOverlapBackslashPatternA()
    -_isOverlapBackslashPatternB()
    -_isOverlapBackslash()
    -_isOverlapSlashPatternA()
    -_isOverlapSlashPatternB()
    -_isOverlapSlash()
    +isOverlap()
    -_defaultYMiddlePoint()
    -_xMiddlePoint()
    +represent3Points()
    +represent4Points()
    -_regularSlashPolyline()
    -_irregularSlashPolyline()
    -_regularBackslashPolyline()
    -_irregularBackslashPolyline()
    -_regularHorizontalPolyline()
    -_irregularHorizontalPolyline()
    -_isIrregularYMid()
    -_wideCircledCornerPolyline()
    -_narrowCircledCornerPolyline()
    +circledCornerPolyline()
    +singleLine()
    +polyline()
}
InterTpLink --|> ForceSimulationLink
class DistanceDiagramBuilder {
    +constructor()
    -_makeNodeCircles()
    -_makeNodeLabels()
    -_makeDistanceCircles()
    -_makeLinkSVGGroup()
    -_convertLinkToPoints()
    -_makeLinkLine()
    -_makeTpTpLinkLine()
    -_makeSupportNodeLinks()
    +isEmptyLayout()
    +makeAllDiagramElements()
}
DistanceDiagramBuilder --|> MultilayerDiagramBase
class DistanceDiagramOperator {
    -_setInitialZoom()
    -_setSVGZoom()
    +targetNodeData()
    -_selectNodeCircleByPath()
    -_selectLinkByPath()
    -_selectNodeLabelByPath()
    -_selectReadyNodeCircle()
    -_selectReadyLink()
    -_selectReadyNodeLabel()
    +highlightNodeCircle()
    +clearHighlight()
    -_clearSelectReady()
    +nodeClickHook()
    +clickHandler()
    -_mouseOverHandler()
    -_mouseOutHandler()
    -_setNodeMouseHandler()
    -_findLinksConnectedWithNode()
    -_selectReadyLinkByNode()
    -_findNodesAtLinkEnd()
    -_linkMouseOverHandler()
    -_setLinkMouseHandler()
    +setAllDiagramElementsHandler()
}
DistanceDiagramOperator --|> DistanceDiagramBuilder
class DistanceDiagramVisualizer {
    +setUISideNodeClickHook()
    +nodeClickHook()
    +highlightByAlert()
}
DistanceDiagramVisualizer --|> DistanceDiagramOperator
class MultilayerDiagramBase {
    +constructor()
    +afterDrawRfcTopologyDataHook()
    +getGraphDataViaGRPC()
    +getGraphDataViaREST()
    +drawRfcTopologyData()
    +makeAllDiagramElements()
    +setAllDiagramElementsHandler()
    +drawRfcTopologyDataAsDiagram()
    -_constructRestURIParams()
    +restURI()
    +splitAlertHost()
    +highlightByAlert()
}
MultilayerDiagramBase --|> DiagramBase
class DiagramBase {
    +makeDiagramContainer()
    +makeRootSVG()
    +resizeRootSVG()
    +isAggregated()
    +isFamilyAggregated()
    +isParentsAggregated()
    -_classOfDiffState()
    -_classOfInactive()
    -_classOfAggregated()
    +classStringFrom()
    +clearDiagramContainer()
    -_clearTooltip()
    -_makeTooltipCreator()
    -_makeClearHighlightButton()
    -_makeToggleDiffButton()
    +makeDiagramControlButtons()
    +controlButtonMouseOverCallback()
    +controlButtonMouseOutCallback()
    -_setClearHighlightButtonHandler()
    -_toggleActiveDiff()
    -_setToggleDiffButtonHandler()
    +setDiagramControlButtonsHandler()
    +clearWarningMessage()
    +makeWarningMessage()
    -_childPathRegexp()
    +matchChildPath()
    +typeOfPath()
    +networkPathOf()
    +parentPathOf()
}
DiagramBase --|> BaseContainer
DiagramBase -- DiffState
DiagramBase -- TooltipCreator
DiagramBase -- RegExp
class TooltipCreator {
    +constructor()
    -_makeTooltip()
    -_isAggregated()
    -_clearTimeout()
    -_enableTooltipForAggregatedNode()
    +enableTooltip()
    -_disableTooltipBody()
    +disableTooltip()
}
TooltipCreator -- AttrClass
class DependencyDiagramBuilder {
    +constructor()
    -_makeNetworkLabelsGroup()
    -_makeNetworkLabels()
    -_makeNetworkElementsGroup()
    -_makeNodeRectsInNetwork()
    -_makeTermPointCirclesInNetwork()
    -_makeNodeLabelsInNetwork()
    -_makeTermPointLabelsInNetwork()
    -_makeDependencyLinesGroup()
    +makeAllDiagramElements()
}
DependencyDiagramBuilder --|> MultilayerDiagramBase
class DependencyDiagramOperator {
    +clearHighlight()
    +clearDependencyLines()
    +clearAllHighlight()
    -_lineConverter()
    -_makeDependencyLines()
    -_pathsFromPairs()
    -_runParentsAndChildren()
    -_markTargetByPaths()
    +clickHandler()
    -_selectReadyByPath()
    -_mouseOverHandler()
    -_mouseOutHandler()
    -_setRootSVGZoom()
    +setAllDiagramElementsHandler()
    -_findElementDataByPath()
    -_getFamilyTree()
}
DependencyDiagramOperator --|> DependencyDiagramBuilder
class DependencyDiagramVisualizer {
    +highlightByAlert()
}
DependencyDiagramVisualizer --|> DependencyDiagramOperator
class Dependency2DiagramBuilder {
    +constructor()
    -_makeNetworkTypeNodeData()
    -_makeNodeDataListOfEachNetworks()
    -_deletePropertiesOf()
    -_rewriteNodeData()
    -_indentOf()
    -_calculateNodePosition()
    +allNodeDataList()
    -_allVisibleNodes()
    -_makeNodeCircles()
    -_makeNodeLabels()
    +refreshDiagramElements()
    -_makeDependencyLineGroup()
    +makeAllDiagramElements()
}
Dependency2DiagramBuilder --|> MultilayerDiagramBase
class Dependency2DiagramOperator {
    +clearHighlight()
    +clearDependencyLines()
    +clearAllHighlight()
    -_setDependencyLineEndpoint()
    -_clearDependencyLineEndpointVisibility()
    -_reCalculateVisibleNodePosition()
    -_lineConverter()
    -_makeDependencyLines()
    -_highlightDependencyLineEndpoint()
    -_refreshDependencyElements()
    -_getFamilyTree()
    -_findNodeDataByPath()
    -_findNetworkDataOwns()
    +clickHandler()
    -_mouseOverHandler()
    -_mouseOutHandler()
    -_moveNetworkLayer()
    -_setAllDiagramElementsHandler()
    -_setRootSVGZoom()
    +setAllDiagramElementsHandler()
}
Dependency2DiagramOperator --|> Dependency2DiagramBuilder
class Dependency2DiagramVisualizer {
    -_findNodeObjByName()
    +highlightByAlert()
}
Dependency2DiagramVisualizer --|> Dependency2DiagramOperator
class ForceSimulationDiagramBuilder {
    +constructor()
    -_makeAllDiagramElements()
    +tpTypeNodes()
    +nodeTypeNodes()
    -_makeInfoTables()
    -_makeNodeInfoTable()
    -_makeTermPointInfoTable()
    +makeDiagramContainer()
    -_makeLinkLines()
    -_makeTermPointCircles()
    -_makeNodeInnerCircles()
    -_makeNodeOuterCircles()
    -_makeTermPointLabels()
    -_makeNodeLabels()
    -_setRootSVGSize()
    -_setCurrentInactiveElementsToInactive()
    -_renameLinkProperty()
}
ForceSimulationDiagramBuilder --|> DiagramBase
class ForceSimulationDiagramOperator {
    +constructor()
    +clearHighlight()
    -_clearSelectReady()
    -_setRootSVGZoom()
    -_idListFromPath()
    +markNodeWith()
    -_markRelateFamilyNodesWith()
    -_markFamilyNodeWith()
    +highlightNode()
    -_cancelClickEvent()
    -_clickOperation()
    -_clickHandler()
    -_doubleClickOperation()
    -_doubleClickHandler()
    -_mouseOverHandler()
    -_mouseOutHandler()
    -_setDiagramElementsHandler()
    -_setNodeInfoTableHandler()
    -_refreshTermPointInfoTable()
    -_appendTermPointInfoTable()
    -_setAllDiagramElementsHandler()
}
ForceSimulationDiagramOperator --|> ForceSimulationDiagramSimulator
class ForceSimulationDiagramVisualizer {
    +constructor()
    +setUISideDrawRfcTopologyHook()
    -_drawRfcTopologyData()
    -_getGraphDataViaGRPC()
    -_getGraphDataViaREST()
    +drawRfcTopologyData()
    -_findNodeDataByPath()
    -_clearAllDiagrams()
    -_drawNetworkDiagrams()
    -_forEachDiagramOperator()
    +clearAllHighlight()
    -_clearAllDiagramsHighlight()
    -_clearAllDiagramsWarningMessage()
    -_findDiagramOperatorByName()
    +highlightByAlert()
}
ForceSimulationDiagramVisualizer --|> BaseContainer
ForceSimulationDiagramVisualizer -- PositionCache
ForceSimulationDiagramVisualizer -- ForceSimulationDiagramOperator
class PositionCache {
    +saveTopology()
    -_loadToNodeData()
    -_loadToNetwork()
    +loadToTopologyData()
}
class ForceSimulationDiagramSimulator {
    +constructor()
    -_makeSimulation()
    -_setupSimulation()
    -_linkDistance()
    -_tickedLink()
    -_tickedTermPoint()
    -_tickedNode()
    -_ticked()
    +startSimulation()
    +stopSimulation()
    +restartSimulation()
}
ForceSimulationDiagramSimulator --|> ForceSimulationDiagramBuilder
class GRPCClient {
    +constructor()
    +getAlerts()
    +getGraphData()
    +graphName()
    +getModels()
}
GRPCClient -- GRPCClient
@enduml
